name: lifx
description: A simple library to interact with LIFX lights. Currently contains 5 methods 
  used to interact with lights. 
homepage: https://github.com/lucaschilders/dart_lifx
version: 0.2.1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  test: ^1.17.12
  convert: ^3.0.1
  json_serializable: ^5.0.0
  hex: ^0.2.0
